from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = true
generate_mono_repository_global_tag = false
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[commit_types]
fix = { changelog_title = "Fixes" }
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }

chore = { changelog_title = "", omit_from_changelog = true }
ci   = { changelog_title = "", omit_from_changelog = true }
build = { changelog_title = "", omit_from_changelog = true }
test = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "mutme"
owner = "vidrl"
authors = [
  { signature = "Eike Steinig", username = "esteinig" }
]

[bump_profiles]

[packages]
